### ISSUE TITLE
Link to plugin's web site is reported as redirected by maven linkcheck plugin.

### ISSUE THREAD

**Issue by MEZk** [mojohaus/xml-maven-plugin#1]
Hello!

We use maven linkcheck plugin to check links on checkstyle's website: http://checkstyle.sourceforge.net/ . The plugin reports that on page http://checkstyle.sourceforge.net/plugins.html the following link is redirected:
http://mojo.codehaus.org/xml-maven-plugin (302 Found) at http://www.mojohaus.org .

Links on plugins.html are generated by Apache Maven Project Info Reports Plugin. All URLs are grabbed from effective POMs of plugins.

Here is the code:

https://github.com/apache/maven-plugins/blob/trunk/maven-project-info-reports-plugin/src/main/java/org/apache/maven/report/projectinfo/PluginsReport.java#L239

https://github.com/apache/maven-plugins/blob/trunk/maven-project-info-reports-plugin/src/main/java/org/apache/maven/report/projectinfo/PluginsReport.java#L269

In effective POM.xml of maven xml plugin the problematic link is:
http://mojo.codehaus.org/xml-maven-plugin

As a result, we do not have an ability to change plugins urls on that page, because those links are specified by plugins developers.

So, please correct the link, because there are contradictions between linkcheck and maven xml plugin.

Thank in advance!

**Comment by jochenw** [comment]
I don't know, what to do here exacty.

**Comment by jochenw** [comment]
I see that you have a fork containing a fix. Care to issue a pull request?

**Comment by jochenw** [comment]
Sorry, accidentally closed. Reopening.

**Comment by MEZk** [comment]
@jochenw 
Fixed
