### ISSUE TITLE
remove dependency on xml-apis which adds xerces and causes some issues

### ISSUE THREAD

**Issue by hboutemy** [mojohaus/xml-maven-plugin#10]
see https://issues.apache.org/jira/browse/MSITE-774
now that Doxia 1.7/maven-site-plugin 3.5.x removed such a dependency on xml-apis, the issue becomes visible (it was not before...)

**Comment by romani** [comment]
@hboutemy , is it possible to release 1.0.2 ? there was no release of this plugin for a while.
