### ISSUE TITLE
Schema detected from xml file

### ISSUE THREAD

**Issue by afrin216** [mojohaus/xml-maven-plugin#12]
Currently we need to specify the schema for xml validation in one way or another. Is it possible to auto-detect the schema from any schema information given in the xml file itself?

**Comment by rosslamont** [comment]
I have created a new open source project ixvc (https://github.com/rosslamont/jxvc) which provides a JAXP compliant validator which can auto detect schema information from an xml file.  It supports the usual suspects, (DTD and XSI) but particularly adds support for ISO/IEC 19757-11:2011 xml-model processing instructions, which in turn can load Relax NG and in theory Schematron and NVDL.  I'd be happy to integrate it to xml-maven-plugin.

**Comment by rosslamont** [comment]
Regarding the original comment, you don't have to specify the schema via the pom.  For normal did and xsd validation (e.g. using psi:schemaLocation in your xml file) it works fine as is.

**Comment by jochenw** [comment]
I assume, this is fixed after pulling in #21?

**Comment by rosslamont** [comment]
@jochenw - by and large. My library doesn't yet have a DTD validator, and won't for a while, but as far as this plugin goes, there's nothing else to do.

**Comment by jochenw** [comment]
Thanks, Ross. That's sufficient, to me, to close this issue and to wait, what will happen.

Cheers!
