### ISSUE TITLE
Sanity checks on mojo parameters missing

### ISSUE THREAD

**Issue by rosslamont** [mojohaus/xml-maven-plugin#16]
There doesn't seem to be much sanity checking of mojo parameters.  For example if I mistype the name of a catalog file, I would expect an error.  The plugin just ignores my catalog.

Similarly, if I mistype the name of a directory in the validation set, the validation plugin does not fail. It does however make a log entry.

**Comment by rosslamont** [comment]
Fixed by pull request #18

**Comment by khmarbaise** [comment]
Thanks for the PR by Ross Lamont.
