### ISSUE TITLE
Add a "strict" setting on all mojo

### ISSUE THREAD

**Issue by rosslamont** [mojohaus/xml-maven-plugin#19]
This particularly relates to catalogs, but could be broadened.

The current implementation will attempt to resolve a schema by catalogue if one is specified, but if that fails, then it will attempt the original URL.  Because that often is a network access, then the build can become exposed to a source of non-determinism.  

A strict flag would require that if a catalog where used, then urls not found in the catalog would result in an error.

**Comment by jochenw** [comment]
Patches welcome.

**Comment by rosslamont** [comment]
@jochenw, thanks for merging all my other changes.

I'll have a go at this in a couple of weeks when the kids are back at school, then perhaps I can ask for a release?

**Comment by jochenw** [comment]
I'd like to see this one going in first, because catalog resolving has always been an issue.

**Comment by rosslamont** [comment]
I'm not sure what the feature should be called - "strict" was simply a starting point, but I think we should use something more specific.  Ideas? I'm thinking "net-isolated", but I don't like that much either.

**Comment by jochenw** [comment]
Suggestion: Option name="catalogHandling", possible values="open" (Use catalog, if possible, but enable collecting to the net, default), or "binding" (Catalog is mandatory, connecting to the net is unsupported).

Nice to have: Specifying catalog entries from the POM.

**Comment by rosslamont** [comment]
I like that approach, what if the values were "pass-through" (or "passThrough") and "strict".

**Comment by rosslamont** [comment]
We could also have "local" which allows file: urls to be resolved.  Overkill?

**Comment by jochenw** [comment]
As long as that's not the default: Okay.

**Comment by rosslamont** [comment]
Not sure why this is still open - it should have auto-closed with the PR.  I'll close it in a few days if there are no comments.

**Comment by jochenw** [comment]
Comments can be added later, so lets close it now. Thank you!
