### ISSUE TITLE
forceCreation is misplaced or misdocumented

### ISSUE THREAD

**Issue by dc55028** [mojohaus/xml-maven-plugin#25]
trying to use the forceCreation option, I saw that it has to be placed in the POM on the same level as TransformationSets, but it is explained among the options of the TransformerSet, so the documentation is misleading.

**Comment by VoldemarLeGrand** [comment]
In other words, [documentaion](http://www.mojohaus.org/xml-maven-plugin/transformation.html) states that `<forceCreation>` option should be placed inside`<transformationSet>`. But actually it should be placed inside `<configuration>` and so is applyed to all `<transformationSet>`'s.

**Comment by jochenw** [comment]
Fix version: 1.0.2
