### ISSUE TITLE
Time for a release.

### ISSUE THREAD

**Issue by G-Ork** [mojohaus/xml-maven-plugin#33]
The last release 1.0.1 is quite old. 
Why so shy?

**Comment by rosslamont** [comment]
Not sure what the delay is, but just found a bug.  I'll fix it and then push for a new release.

**Comment by rosslamont** [comment]
1.0.2.-beta-1 released - announcement coming soon.

**Comment by jochenw** [comment]
Thanks very much, that is good news!

Jochen
