### ISSUE TITLE
NullPointerException when setting "addedToClassPath=true" without specifying output directory

### ISSUE THREAD

**Issue by fbilhautcmx** [mojohaus/xml-maven-plugin#41]
`Caused by: java.lang.NullPointerException
	at org.codehaus.mojo.xml.TransformMojo.addToClasspath(TransformMojo.java:253)
	at org.codehaus.mojo.xml.TransformMojo.transform(TransformMojo.java:569)
	at org.codehaus.mojo.xml.TransformMojo.execute(TransformMojo.java:632)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more`

**Comment by rosslamont** [comment]
I'm not super familiar with the transform goal, but I'll have a go at it.

Can I assume you explicitly set the output directory to null? It's supposed to default if not supplied.

If so, should this fail as a configuration error?

**Comment by fbilhautcmx** [comment]
Le 23 févr. 2018 à 23:08, Ross Lamont <notifications@github.com> a écrit :
> I'm not super familiar with the transform goal, but I'll have a go at it.
> 
Thanks !
> Can I assume you explicitly set the output directory to null? It's supposed to default if not supplied.
> 
> If so, should this fail as a configuration error?
> 


Actually not, the output dir option was not supplied at all. I was surprised as I saw there was a default value, but I assume the variable is actually null and the default value is managed afterwards.

When supplied explicitly the parameter with its default value, it works :

<outputDir>${project.build.directory}/generated-resources/xml/xslt</outputDir>
<addedToClasspath>true</addedToClasspath>

**Comment by jochenw** [comment]
On Fri, Feb 23, 2018 at 11:08 PM, Ross Lamont <notifications@github.com>
wrote:

> Can I assume you explicitly set the output directory to null? It's
> supposed to default if not supplied.
>
>
> And, how would one do that, because Maven is handling the default values?

Jochen

**Comment by rosslamont** [comment]
> And, how would one do that, because Maven is handling the default values?

`<outputDir></outputDir>`

Presumably by mistake.

Sounds like the defaulting isn't working for some reason.

**Comment by rosslamont** [comment]
In a comment on issue #40 jochenw said:

> Otoh, if the default is actually ignored when using something like
>
>  `<outputDir/>`
>
>then I'd definitely suggest that you file a Maven issue, because that is
clearly in violation of the plugin contract.

If a developer explicitly sets something to null, then surely this should override the default?  In this particular case that would be an error so I'm not in a great rush to do anything about it.
