### ISSUE TITLE
Includes element is not cumulative

### ISSUE THREAD

**Issue by delanym** [mojohaus/xml-maven-plugin#45]
The <includes/> element is described:

> Specifies a pattern of files, which are being included. By default, all files are included. The pattern is relative to the directory given by "dir". This element may be repeated as much as needed.

However it doesn't function as expected. If the element is repeated, the previous value is lost to the next. I tried including multiple patterns in a single element but only the last works:

```
<includes>xsd/drones.xsd|xsd/globals.xsd</includes>
<includes>xsd/drones.xsd; xsd/globals.xsd</includes>
<includes>xsd/drones.xsd xsd/globals.xsd</includes>
<includes>xsd/(drones.xsd|globals.xsd)</includes>
<includes>xsd/(*.xsd)</includes>
<includes>xsd/*.xsd</includes>
```

So if I want a file from two different directories I have to unpack the whole parent directory.

Please define a repeatable <include/> element.

**Comment by jochenw** [comment]
As already requested: Please provide a complete "configuration" element as a sample.

**Comment by delanym** [comment]
`<configuration>
<artifactItems>
<artifactItem>
<groupId>org.codehaus.mojo</groupId>
<artifactId>xml-maven-plugin</artifactId>
<version>1.0.2</version>
<type>jar</type>
</artifactItem>
</artifactItems>
<includes>**/*.xml</includes>
<includes>**/*.class</includes>
<outputDirectory>${project.basedir}/target/pieces</outputDirectory>
</configuration>`

**Comment by jochenw** [comment]
Try
```
  <includes>
    <include>**/*.xml</include>
    <include>**/*.class</include>
  </includes>
```

**Comment by delanym** [comment]
Unable to parse configuration of mojo org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack: Basic element 'includes' must not contain child elements -> [Help 1]

**Comment by jochenw** [comment]
Sorry, but so far I still don't know what you are attempting to do. (In fact, I don't even know whether you are running xml:check, or xml:transform.) I really need a complete example. What you are giving above, is not.

**Comment by jochenw** [comment]
Whether you see the reason for confusion, or not, isn't relevant. Fact is, whether you accept it, or not: I can't, and won't continue without a complete POM (as attachment), or, at the very least, a complete build/plugins/plugin segment from the POM. That is a trivial request, and I fail to see any difficulties in fulfilling it. You are using a software, and its documentation, that took a lot of hours of work, and you are not even ready to spend a few minutes to see your issue resolved?

Apart from that: The link to stackoverflow, that you provide above, is about the maven-dependency-plugin, and not the xml-maven-plugin. Are you deliberately confusing?

**Comment by delanym** [comment]
That's it - wrong plugin. Thanks for your diligence.

**Comment by rosslamont** [comment]
So, should we close this? I guess we could improve the documentation slightly to make the includes and excludes sections a bit clearer.  Happy to do this...

**Comment by jochenw** [comment]
Closing.
