### ISSUE TITLE
Change XDoclet to annotations

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/xml-maven-plugin#5]

**Comment by jochenw** [comment]
Fix ready for commit. Waiting for the required permissions to push.

**Comment by jochenw** [comment]
Just committed, closing.

**Comment by jochenw** [comment]
@khmarbaise 
I have created a new branch github-5. When running the integration tests in that branch, I get the following errors in the invokers build.log:

[ERROR] Failed to execute goal org.codehaus.mojo:xml-maven-plugin:1.0.1-SNAPSHOT:validate (default-cli) on project it1: The parameters 'locator' for goal org.codehaus.mojo:xml-maven-plugin:1.0.1-SNAPSHOT:validate are missing or invalid -> [Help 1]


I have no idea, what the problem with injecting the ResourceManager is. Could you please be so kind and look into that?

**Comment by khmarbaise** [comment]
Fixed the whole branch and created the travis build and let CI check the contents of master. Master has now the content of the github-5 branch. Builds all green.
