### ISSUE TITLE
Using Saxon 9.x with TransformationSet goal transform

### ISSUE THREAD

**Issue by mricaud** [mojohaus/xml-maven-plugin#50]
Hi

I would need to use a recent version of Saxon in my transformationSets.
As explained in the [documentation ](http://www.mojohaus.org/xml-maven-plugin/examples/transform-saxon.html) I set this dependency: 
```xml
<dependency>
    <groupId>net.sf.saxon</groupId>
    <artifactId>Saxon-HE</artifactId>
    <version>9.8.0-12</version>
    <type>jar</type>
</dependency>
```
In my XSL I send this message: 
```xml
<xsl:message>xsl:product-version = <xsl:value-of select="system-property('xsl:product-version')"/></xsl:message>
```

And I always get 8.7 (instead of what I expected "9.8.0-12")

Does anybody knows about this limitation?

Thanks in advance
Cheers

Matthieu

**Comment by jochenw** [comment]
Hi, Matthieu,

I notice that the version 8.7 is the same than the one being used. Is it
possible, that you have declared more than one dependency?

Jochen

**Comment by mricaud** [comment]
Hi Jochen, you are perfectly right!
I really thought there were a limitation in the plugin, but when creating a simple use case I finally had the good Saxon called.
That must be something in my real project making a double dependency to Saxon.

After investigating I found it: I use the same plugin for validating RNG files soI add 2 other dependencies.
My all dependencies into the plugin are:
```xml
<dependencies>
  <dependency>
    <groupId>com.componentcorp.xml.validation</groupId>
    <artifactId>jxvc</artifactId>
    <version>0.9.4</version>
  </dependency>
  <dependency>
    <groupId>com.componentcorp.xml.validation</groupId>
    <artifactId>relaxng</artifactId>
    <version>0.9.4</version>
  </dependency>
  <dependency>
      <groupId>net.sf.saxon</groupId>
      <artifactId>Saxon-HE</artifactId>
      <version>9.8.0-12</version>
      <type>jar</type>
    </dependency>
</dependencies>
```
In this configuration I always get Saxon 8.7 as message.

When I comment the jxvc dependency I get the good 9.8.0-12 Saxon.

Do you know how I can force the use of my Saxon dependency ?
or shall I close this issue and open a new one in JXVC ?
@rosslamont maybe you can help me on this topic ?

Here is a simple zip for repro: [issue50.zip](https://github.com/mojohaus/xml-maven-plugin/files/2185781/issue50.zip)

Cheers
Matthieu

**Comment by jochenw** [comment]
What I still do not get completely, Matthieu: Where do you have the Saxon dependency? Is it in the plugins private dependency list, as suggested in the documentation snippet that you quote? Or is it in the projects dependency list?

Thanks,

Jochen

**Comment by jochenw** [comment]
Sorry, found your attachment. So, you are using the plugins dependency list. Good! Now, if any of the dependencies with groupId=com.componentcorp.xml.validation (That's your Stuff, Ross?) us using Saxon 8.7 as a dependency, then dependency exclusions on the respective entry should indeed be the way to go.

**Comment by mricaud** [comment]
Hi guys ! Lately (sorry for that) I tried the dependency exclusion with :
`<dependency>
  <groupId>com.componentcorp.xml.validation</groupId>
  <artifactId>relaxng</artifactId>
  <version>0.9.4</version>
  <exclusions>
    <exclusion>
      <groupId>net.sf.saxon</groupId>
      <artifactId>saxon</artifactId>
    </exclusion>
  </exclusions>
</dependency>`

It works well, the xsl message is now Saxon 9.8 !

>[INFO] --- xml-maven-plugin:1.0.2:transform (default) @ issue50 ---
>[INFO] Transforming file: C:\Users\mricaud\_WORK\_github\xml-maven-plugin.mojo.issue50_transformation-saxon-version\src\main\xml\doc1.xml
> **xsl:product-version = HE 9.8.0.12**
> [INFO] Transformed 1 file(s).

Thanks both for your help !

Matthieu
