### ISSUE TITLE
formatFileSet/directory vs. validationFileSet/dir inconsistency

### ISSUE THREAD

**Issue by sewe** [mojohaus/xml-maven-plugin#54]
`<formatFileSet>` has (like `project/build/resources/resource`) a `directory` property, whereas `<validationSet>` and `<transformationSet>` have a `dir` (and in the latter case: `outputDir` property). This is rather inconsistent.

It would be nice if the definitions of the various `*Set`s used by the `xml-maven-plugin` were a bit more consistent.

**Comment by jochenw** [comment]
On Fri, Nov 1, 2019 at 11:45 AM Andreas Sewe <notifications@github.com>
wrote:

> <formatFileSet> has (like project/build/resources/resource) a directory
> property, whereas <validationSet> and <transformationSet> have a dir (and
> in the latter case: outputDir property). This is rather inconsistent.
>
> It would be nice if the definitions of the various *Sets used by the
> xml-maven-plugin were a bit more consistent.
>
>
> You are right about the inconsistency. That being said: Do you see a
possibility to fix this in a manner, which is upwards compatible?

Because incompatibilities are the bigger problem, compared to
inconsistencies.

Jochen

**Comment by jochenw** [comment]
No response to my question from more than one year ago. Closing.
